-- ==============================================================
-- 범용 WBS 일정 분석 프로그램 — 신규 테이블 설정
-- 기존 wbs_members / wbs_analyses 테이블과 별개로 생성합니다.
-- ==============================================================

-- 1. 프로젝트 목록
create table if not exists public.wbs_gen_projects (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  name        text not null,
  description text,
  start_date  date,
  end_date    date
);

alter table public.wbs_gen_projects enable row level security;
drop policy if exists "gen projects select" on public.wbs_gen_projects;
create policy "gen projects select" on public.wbs_gen_projects for select using (true);
drop policy if exists "gen projects insert" on public.wbs_gen_projects;
create policy "gen projects insert" on public.wbs_gen_projects for insert with check (true);
drop policy if exists "gen projects update" on public.wbs_gen_projects;
create policy "gen projects update" on public.wbs_gen_projects for update using (true);
drop policy if exists "gen projects delete" on public.wbs_gen_projects;
create policy "gen projects delete" on public.wbs_gen_projects for delete using (true);


-- 2. 프로젝트별 구성원
create table if not exists public.wbs_gen_members (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id  bigint not null references public.wbs_gen_projects(id) on delete cascade,
  name        text not null,
  role        text,
  email       text not null,
  phone       text,
  title       text
);

create index if not exists wbs_gen_members_project_id_idx on public.wbs_gen_members (project_id);

alter table public.wbs_gen_members enable row level security;
drop policy if exists "gen members select" on public.wbs_gen_members;
create policy "gen members select" on public.wbs_gen_members for select using (true);
drop policy if exists "gen members insert" on public.wbs_gen_members;
create policy "gen members insert" on public.wbs_gen_members for insert with check (true);
drop policy if exists "gen members update" on public.wbs_gen_members;
create policy "gen members update" on public.wbs_gen_members for update using (true);
drop policy if exists "gen members delete" on public.wbs_gen_members;
create policy "gen members delete" on public.wbs_gen_members for delete using (true);


-- 3. 프로젝트별 WBS 분석 결과
create table if not exists public.wbs_gen_analyses (
  id          bigint generated by default as identity primary key,
  saved_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id  bigint not null references public.wbs_gen_projects(id) on delete cascade,
  wbs_date    date not null,
  file_name   text not null,
  file_data   text,
  tasks       jsonb not null default '[]'::jsonb,
  summary     jsonb not null default '{}'::jsonb
);

create index if not exists wbs_gen_analyses_project_id_idx on public.wbs_gen_analyses (project_id, wbs_date desc);

alter table public.wbs_gen_analyses enable row level security;
drop policy if exists "gen analyses select" on public.wbs_gen_analyses;
create policy "gen analyses select" on public.wbs_gen_analyses for select using (true);
drop policy if exists "gen analyses insert" on public.wbs_gen_analyses;
create policy "gen analyses insert" on public.wbs_gen_analyses for insert with check (true);
drop policy if exists "gen analyses update" on public.wbs_gen_analyses;
create policy "gen analyses update" on public.wbs_gen_analyses for update using (true);
drop policy if exists "gen analyses delete" on public.wbs_gen_analyses;
create policy "gen analyses delete" on public.wbs_gen_analyses for delete using (true);
