-- ==============================================================
-- 1. 구성원 관리 (wbs_members) 테이블 생성 및 RLS 정책 설정
-- ==============================================================
create table if not exists public.wbs_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  email text not null,
  phone text,
  title text
);

-- RLS(Row Level Security) 활성화
alter table public.wbs_members enable row level security;

-- 모든 사용자에게 조회, 등록, 수정, 삭제 허용 정책 설정
drop policy if exists "Allow public read access on members" on public.wbs_members;
create policy "Allow public read access on members" on public.wbs_members for select using (true);
drop policy if exists "Allow public insert access on members" on public.wbs_members;
create policy "Allow public insert access on members" on public.wbs_members for insert with check (true);
drop policy if exists "Allow public update access on members" on public.wbs_members;
create policy "Allow public update access on members" on public.wbs_members for update using (true);
drop policy if exists "Allow public delete access on members" on public.wbs_members;
create policy "Allow public delete access on members" on public.wbs_members for delete using (true);


-- ==============================================================
-- 2. WBS 분석 결과 테이블 생성 및 RLS 정책
-- ==============================================================
create table if not exists public.wbs_analyses (
  id bigint generated by default as identity primary key,
  saved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  wbs_date date not null,
  file_name text not null,
  file_data text,
  tasks jsonb not null default '[]'::jsonb,
  summary jsonb not null default '{}'::jsonb
);

-- Existing installations may have a shorter column type; normalize it for Base64 Excel data.
alter table public.wbs_analyses alter column file_data type text;

create index if not exists wbs_analyses_wbs_date_idx on public.wbs_analyses (wbs_date desc);

alter table public.wbs_analyses enable row level security;

drop policy if exists "Allow public read access on analyses" on public.wbs_analyses;
create policy "Allow public read access on analyses" on public.wbs_analyses for select using (true);
drop policy if exists "Allow public insert access on analyses" on public.wbs_analyses;
create policy "Allow public insert access on analyses" on public.wbs_analyses for insert with check (true);
drop policy if exists "Allow public update access on analyses" on public.wbs_analyses;
create policy "Allow public update access on analyses" on public.wbs_analyses for update using (true);
drop policy if exists "Allow public delete access on analyses" on public.wbs_analyses;
create policy "Allow public delete access on analyses" on public.wbs_analyses for delete using (true);


-- ==============================================================
-- 2. WBS Excel 파일 저장용 스토리지 버킷 (wbs-files) 생성 및 정책 설정
-- ==============================================================

-- 스토리지 버킷 삽입 (wbs-files)
-- storage.objects 테이블에 대한 버킷 RLS 정책 설정 (익명 사용자 업로드/다운로드 가능)
-- New uploads are stored directly in public.wbs_analyses.file_data (Base64),
-- so no Storage bucket or storage.objects policy is required.
